### ISSUE TITLE
shared object ‘Pmax2.so’ not found when install graphclass

### ISSUE THREAD

**Issue by VealM** [jesusdaniel/graphclass#1]
Dear jesusdaniel,
         Hi, when I installed your package according to ReadMe

        ``` shell
        library(devtools)
         install_github("jesusdaniel/graphclass")
         ```
         I am sure that the installation of R and devtools  was successful.
         But there just something went wrong  when I installed graphclass.
         Here is the error log for failure of installation of graphclass
         
[log.txt](https://github.com/jesusdaniel/graphclass/files/4270238/log.txt)
        It tells me that  shared object Pmax2.so not found, however I just found it in your repo at src/Pmax2.so
       Could you please help me solve the problems?
       thanks for your help!
       Platform CentOS-7 ,R-3.6.0

**Comment by jesusdaniel** [comment]
Thanks for your question, I'll take a look and try to figure out what is the problem.

**Comment by VealM** [comment]
> Thanks for your question, I'll take a look and try to figure out what is the problem.

Thank you!  I'm looking forward to your reply~

**Comment by jesusdaniel** [comment]
I've been trying to solve this problem. At the moment, I am able to install the package with no problems on MacOs, but not on Windows, which gives me the same problem with the shared object Pmax2.so. I'm still trying to figure out what could be the problem. In the meantime, can you please check if you have installed a GNU C++ compiler? [(see 3) here](https://www.nceas.ucsb.edu/scicomp/usecases/CreateRPackageWithC)

**Comment by VealM** [comment]
> I've been trying to solve this problem. At the moment, I am able to install the package with no problems on MacOs, but not on Windows, which gives me the same problem with the shared object Pmax2.so. I'm still trying to figure out what could be the problem. In the meantime, can you please check if you have installed a GNU C++ compiler? [(see 3) here](https://www.nceas.ucsb.edu/scicomp/usecases/CreateRPackageWithC)

Thanks for your time and efforts! Yeah, I have installed a GNU C++ compiler whose version is *gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)*.  
I just read the link you  recommended. I feel it hard for me to configure  R software development tools  according to 3 from the link , since my server system distribution is CentOs not Ubuntu (but I‘m sure that GCC also works right on the platform).   
Problems like these sometimes really sounds annoying.  Actually I am new to R (graphclass is really helpful for my friend but she installed it on Windows 10 and failed, so she comes to me for help). I wanna devote to compiling graphclass when I know more  about R. Looking forward to graphclass release for Linux and Win!

**Comment by jesusdaniel** [comment]
Hi @VealM , I fixed the problem on Windows, and now I've tested it on Windows and MacOS and it works fine. It seems that the problem for Windows had to do with some conflicts in the names and the references of the C files. I changed the file name to the package name, and now the problem is solved. 
I'll really appreciate if you let me know whether you are able to install it now. Thanks!

**Comment by VealM** [comment]
Thanks! I just reinstalled graphclass on  my server and  it really works fine.  I believe more people will benefit from graghclass because of your great contributions to it!

**Comment by jesusdaniel** [comment]
Thanks for your interest and your feedback! Please let me know if you find any issues in the future.
