### ISSUE TITLE
Graph edge weights

### ISSUE THREAD

**Issue by ichcha-m** [jesusdaniel/graphclass#2]
Hello,

Thank you for making the fMRI datasets available for use. In the arxiv paper, several steps of pre-processing have been listed. Could you tell me whether the the edge weights of the networks in the COBRE dataset (in the package) are the Fisher-transformed correlation values or if they were further processed in any way? 

Thanks,
Ichcha

**Comment by jesusdaniel** [comment]
Hello Ichcha,

Thanks for your question. The edge weights are the Fisher-transformed correlations. I'm going to update the README and the manual to include this information.

Best,
Jesús

**Comment by ichcha-m** [comment]
Hi Jesús, 

Thanks for the clarification!

Ichcha
